repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        language: system
        entry: ruff format
        types_or: [ python, jupyter ]
      - id: ruff-check
        name: ruff-check
        language: system
        entry: ruff check
        types_or: [ python, jupyter ]
